apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREF5TURZdwpOekUyTkRKYUZ3MDBOREF5TURZd056RTJOREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDNzhRcnZQdzRHZ1ZGNmdPbEFpRy9laXdCcWFjdm9LeWRHYlROV1g3djI2LzlCOTczOQpSNHdVYkgxT1R2L3cvanlua1VpSndVbEJTRFlocTNrQ3dvWXZORktqc1A4MVovcTJINUF5Q29UVnVQME9HNGpxCnVZOFprYXVKTjJ1WGJPenBvYU5zaFRLNXo1cGVHVHduc1F2V1RZaXAyWlZBWWF1SkZqU3lLRFRUWTBoSjN0R3MKS0Y2ME1RZjNIUjkyVTFuaWhwTFA2cFIrT3U4UTBDaDQvRWlNbVBMRmsrdGlIVEN1Mk5QVWE5WDM0OWplOHRXdApaV1lIUXQyQlZRYWNIV3llY01lWURpWTRRa0V2OXdnaUJScHM0cW9HM095dzFSeHM4ditPOTZMRGRGcXQyazYyCnpBSG9PY25hQnRzVTk0TDBNU0h4WkNSM1B2OHdxdGRTTWR2UEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFxVU1qbXR3MTNWQlFMY3hTQgppclkxc3duQ2xUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFkdFBwekVHUTI5d1JscTFabWNrSkZsMzQ2VFBOCkF5eWdrd2hPR0tkRlcyUXRKNGErcU56b1Y5MEJKQWZyU1NHQmRvSGVPNnN5NWMrbGIzaFh5MFNnYlJGdFE1TUMKWTN6bUNpZEV4UjlRTW1CTkR0eEQrT2VveFlRamF2SVNFdDRzVHN4a0ZVSG9MelUrcEZtMXI0RnFOSmpkK3N3TwpXRk9RQXMrMUs4TitxMlhIeWlFekNXbmExZzV0cTZTUHUwNGxuem05WEpvNEJ3UnFnL2ljVEJpaDVubHhtVlJkCjRaaTZmRXBUQUM4WWdPVnBNUzlZNTE2NEdINHd1azdQVGhNZ1NxSGlvbkp6MFo3MHFnOGJidkN6OFFKcXNPbU8KNFpGUkZEa3dHenhTRTNzVkpmbU1NVDk3ZCtNaHZMNjNCSFlNQ0xDbFpvVTFlQ1Z2NWNIZXJERFY3QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e973a24b-6c66-4615-85c6-2a7f9458e07e.k8s.ondigitalocean.com
  name: do-sgp1-my-k8s-cluster
contexts:
- context:
    cluster: do-sgp1-my-k8s-cluster
    user: do-sgp1-my-k8s-cluster-admin
  name: do-sgp1-my-k8s-cluster
current-context: do-sgp1-my-k8s-cluster
kind: Config
preferences: {}
users:
- name: do-sgp1-my-k8s-cluster-admin
  user:
    token: dop_v1_ed644cc90fc78a67506760874209a404a711293da79d3848da5d2b1b8eb9f9e0
